version: '3.8'

services:
  frontend:
    image: devops/frontend:latest
    networks:
      - app-net

  backend:
    image: devops/backend:latest
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/defects_db"
      PORT: 3000
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: defects_db
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: overlay

volumes:
  postgres_data:
