# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x10\n\x0eRollDieRequest\" \n\x0fRollDieResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x45\n\x0b\x44iceService\x12\x36\n\x07RollDie\x12\x13.api.RollDieRequest\x1a\x14.api.RollDieResponse\"\x00\x42\x0cZ\nserver/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nserver/api'
  _globals['_ROLLDIEREQUEST']._serialized_start=18
  _globals['_ROLLDIEREQUEST']._serialized_end=34
  _globals['_ROLLDIERESPONSE']._serialized_start=36
  _globals['_ROLLDIERESPONSE']._serialized_end=68
  _globals['_DICESERVICE']._serialized_start=70
  _globals['_DICESERVICE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
